CSDN/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),


    path('', include('blog.urls')),
    path('auth/', include('bzdauth.urls')),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('blog/detail/<int:blog_id>', views.blog_detail, name='blog_detail'),
    path('blog/pub', views.pub_blog, name='pub_blog'),
    path('blog/comment/pub', views.pub_comment, name='pub_comment'),
    path('search', views.search, name='search')
]

bzdauth/urls.py
from django.urls import path
from . import views

app_name = 'bzdauth'
urlpatterns = [
    # path('', views.index, name='index'),
    path('login', views.bzdlogin, name='login'),
    path('logout', views.bzdlogout, name='logout'),
    path('register', views.register, name='register'),
    path('captcha', views.send_email_captcha, name='email_captcha'),
]

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class BlogCategory(models.Model):
    name = models.CharField(max_length=200, verbose_name='分类名称')

    def __str__(self):
        return self.name

    class Meta:
        # apple, apples
        verbose_name = '博客分类'
        verbose_name_plural = verbose_name


class Blog(models.Model):
    title = models.CharField(max_length=200, verbose_name='标题')
    content = models.TextField(verbose_name='内容')
    pub_time = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    category = models.ForeignKey(BlogCategory, on_delete=models.CASCADE, verbose_name='分类')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='作者')

    def __str__(self):
        return self.title

    class Meta:
        # apple, apples
        verbose_name = '博客'
        verbose_name_plural = verbose_name
        ordering = ['-pub_time']  # 负号倒序排序


class BlogComment(models.Model):
    content = models.TextField(verbose_name='内容')
    pub_time = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments', verbose_name='所属博客')  #related_name为反向拿到评论的名字.此外django自带方法blog.blogcomment_set
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='作者')

    def __str__(self):
        return self.content

    class Meta:
        # apple, apples
        verbose_name = '评论'
        verbose_name_plural = verbose_name
        ordering = ['-pub_time']

bzdauth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class CaptchaModle(models.Model):
    email=models.EmailField(unique=True)
    captcha = models.CharField(max_length=4)
    create_time = models.DateTimeField(auto_now_add=True)

blog/forms.py
from django import forms


class PubBlogForm(forms.Form):
    title = forms.CharField(max_length=200, min_length=2)
    content = forms.CharField(min_length=2)
    category = forms.IntegerField()

blog/views.py
from django.shortcuts import render, reverse, redirect
from django.http.response import JsonResponse
from django.contrib.auth.decorators import login_required
from django.urls.base import reverse_lazy
from django.views.decorators.http import require_http_methods, require_POST, require_GET
from .models import BlogCategory, Blog, BlogComment
from .forms import PubBlogForm
from django.db.models import Q  # 理解:Q表达式使得数据可以进行'与','或'运算(&,|)
def index(request):
    blogs = Blog.objects.all()
    return render(request, 'index.html', context={"blogs": blogs})

def blog_detail(request, blog_id):
    try:
        blog = Blog.objects.get(pk=blog_id)  # pk是主键的缩写
    except Exception as e:
        blog = None  # 此处可设置404页面
    return render(request, 'blog_detail.html', context={'blog': blog})

@require_http_methods(['GET', 'POST'])
@login_required(login_url=reverse_lazy("bzdauth:login"))  # 在页面加载后再去加载路由，否则可能路由还没进内存读不到
def pub_blog(request):
    if request.method == 'GET':
        categories = BlogCategory.objects.all()
        return render(request, 'pub_blog.html', context={"categories": categories})
    else:
        form = PubBlogForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            content = form.cleaned_data.get('content')
            category_id = form.cleaned_data.get('category')
            blog = Blog.objects.create(title=title, content=content, category_id=category_id, author=request.user)
            return JsonResponse({"code": 200, "message": "博客发布成功", "data": {"blog_id": blog.id}})
        else:
            print(form.errors)
            return JsonResponse({'code': 400, "message": "参数错误"})


@require_POST
@login_required()
def pub_comment(request):
    blog_id = request.POST.get('blog_id')
    content = request.POST.get('content')
    BlogComment.objects.create(content=content, blog_id=blog_id, author=request.user)
    # 重新加载博客详情页
    return redirect(reverse("blog:blog_detail", kwargs={'blog_id': blog_id}))


@require_GET
def search(request):
    # /search?q=xxx 希望通过此方式查找
    q = request.GET.get('q')
    # 从博客的标题和内容中查找含有q关键字的博客
    blogs = Blog.objects.filter(Q(title__icontains=q)|Q(content__icontains=q)).all()
    return render(request, 'index.html', context={"blogs": blogs})

bzdauth/views.py
from django.shortcuts import render, redirect, reverse
from django.http.response import JsonResponse
import string
import random
from django.core.mail import send_mail
from .models import CaptchaModle
from django.views.decorators.http import require_http_methods
from .form import RegisterForm, LoginForm
from django.contrib.auth import get_user_model, login, logout  #此处login仅在使用默认django给的user对象时，可用，若用户自定义对象则不可用这个login



User = get_user_model()

@require_http_methods(['GET', 'POST'])
def bzdlogin(request):
    if request.method == 'GET':
        return render(request, 'login.html')
    else:
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            remember = form.cleaned_data.get('remember')
            user = User.objects.filter(email=email).first()
            if user and user.check_password(password):
                # 登录
                login(request, user)
                # 判断是否14天免登录
                if not remember:
                    # 如果没有点击免登录，设置过期时间为0，即浏览器关闭后密码过期
                    request.session.set_expiry(0)
                    # 如果点击了，无操作，使用默认的2周过期时间
                return redirect('/')
            else:
                print('邮箱或密码错误')
                return redirect(reverse('bzdauth:login'))

def bzdlogout(request):
    logout(request)
    return redirect("/")

@require_http_methods(['GET','POST'])
def register(request):
    if request.method == 'GET':
        return render(request,'register.html')
    else:
        form = RegisterForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            User.objects.create_user(email=email, username=username, password=password)
            return redirect(reverse('bzdauth:login'))
        else:
            print(form.errors)
            return redirect(reverse('bzdauth:register'))


def send_email_captcha(request):
    # ?email=xxx使用查询参数表达式
    email = request.GET.get('email')
    if not email:
        return JsonResponse({"code":400,"message":"请输入正确的邮箱"})
    #生成验证码（取随机四位数）因取得数字由列表形式排列，依次使用连接来合并成四位数
    captcha="".join(random.sample(string.digits,k=4))
    # 储存到数据库中(本项目体量较小为方便直接存储数据库，不使用缓存)
    CaptchaModle.objects.update_or_create(email=email, defaults={ 'captcha': captcha})
    send_mail(subject='不知冬的博客注册验证码', message=f"您的注册验证码是：{captcha}", recipient_list=[email], from_email=None)
    return JsonResponse({"code":200,"message":"邮箱验证码发送成功"})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}-不知冬的博客</title>
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block  head%}{% endblock %}<!-- 后续可添加额外内容 -->
</head>
<body>

<header class="p-3 text-bg-info border-bottom border-warning mb-4">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img src="{% static 'image/lafei.png' %}" height="45" alt="">
                <!-- alt参数指定图片的替代文字，如果图片无法加载，浏览器会显示这个文本 -->
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="/" class="nav-link px-2 text-secondary">首页</a></li>
                <li><a href="{% url 'blog:pub_blog' %}" class="nav-link px-2 text-light">发布博客</a></li>

            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" action="{% url 'blog:search' %}" method="get">
                <input type="search" name="q" class="form-control form-control-dark text-bg-light" placeholder="搜索..."
                       aria-label="Search">
            </form>

            {% if user.is_authenticated %}
                <div class="dropdown text-end">
                    <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{% static 'image/zhen1.png' %}" alt="mdo" width="32" height="32"
                             class="rounded-circle">
                    </a>
                    <ul class="dropdown-menu text-small" style="">
                        <li><a class="dropdown-item" href="{% url 'bzdauth:logout' %}">退出登录</a></li>
                    </ul>
                </div>
            {% else %}
                <div class="text-end">
                    <a href="{% url 'bzdauth:login' %}" type="button" class="btn btn-warning me-2">登录</a>
                    <a href="{% url 'bzdauth:register' %}" type="button" class="btn btn-outline-light">注册</a>
                </div>
            {% endif %}

        </div>
    </div>
</header>
<main class="container bg-white p-3 rounded">
    {% block main %}
    {% endblock %}

</main>
</body>
</html>

templates/blog_detail.html
{% extends 'base.html' %}

{% block head %}
    <link rel="stylesheet" href="{% static 'highlight/styles/github-dark.min.css' %}">
    <script src="{% static 'highlight/highlight.min.js' %}"></script>
{% endblock %}

{% block main %}
	<h1>{{ blog.title }}</h1>
    <hr>
    <div class="mt-2">
        <img src="{% static 'image/zhen1.png' %}" class="rounded-circle" width="30" height="30" alt="">
        <span class="ms-2">{{ blog.author.username }}</span>
        <span class="ms-2">于</span>
        <span class="ms-2">{{ blog.pub_time|date:"Y年m月d日 H时i分" }}</span>发布
    </div>
    <hr>
    <div class="py-2">
        {{ blog.content|safe }}
    </div>
    <hr>
    <div class="mt-2">
        <h3>评论（{{ blog.comments.all|length }}）</h3>
        <form action="{% url 'blog:pub_comment' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="blog_id" value="{{ blog.id }}">
            <div class="mt-2">
                <input type="text" class="form-control" placeholder="请输入评论" name="content">
            </div>
            <div class="text-end mt-2">
                <button type="submit" class="btn btn-primary">评论</button>
            </div>
        </form>
    </div>
    <div class="mt-2">
        <ul class="list-group list-group-flush">
            {% for comment in blog.comments.all %}
                <li class="list-group-item">
                    <div class="d-flex justify-content-between text-body-secondary">
                        <div class="user-info">
                            <img src="{% static 'image/zhen1.png' %}" class="rounded-circle" height="40" width="40"
                                 alt="">
                            <span class="mt-2">{{ comment.auther.username }}</span>
                        </div>
                        <div class="creat-time" style="line-height: 40px">{{ comment.pub_time|date:"Y年m月d日 H时i分" }}</div>
                    </div>
                    <div class="mt-3">{{ comment.content }}</div>
                </li>
            {% endfor %}
        </ul>
    </div>
    <script>
        hljs.highlightAll();
    </script>
{% endblock %}

templates/html备份/blog_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>不知冬的博客</title>
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>

<header class="p-3 text-bg-info border-bottom border-warning mb-4">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img src="{% static 'image/lafei.png' %}" height="45" alt="">
                <!-- alt参数指定图片的替代文字，如果图片无法加载，浏览器会显示这个文本 -->
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="#" class="nav-link px-2 text-secondary">首页</a></li>
                <li><a href="#" class="nav-link px-2 text-light">发布博客</a></li>

            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                <input type="search" class="form-control form-control-dark text-bg-light" placeholder="搜索..."
                       aria-label="Search">
            </form>

            <div class="text-end">
                <button type="button" class="btn btn-warning me-2">登录</button>
                <button type="button" class="btn btn-outline-light">注册</button>
            </div>
        </div>
    </div>
</header>
<main class="container bg-white p-3 rounded">
    <h1>博客详情_Django基础</h1>
    <hr>
    <div class="mt-2">
        <img src="{% static 'image/zhen1.png' %}" class="rounded-circle" width="30" height="30" alt="">
        <span class="ms-2">鸩</span>
        <span class="ms-2">于</span>
        <span class="ms-2">2024年12月26日 16:06</span>发布
    </div>
    <hr>
    <div class="py-2">
        这是博客详情
    </div>
    <hr>
    <div class="mt-2">
        <h3>评论(10)</h3>
        <form action="" method="POST">
            <div class="mt-2">
                <input type="text" class="form-control" placeholder="请输入评论">
            </div>
            <div class="text-end mt-3">
                <button type="button" class="btn btn-primary">Primary</button>
            </div>
        </form>
    </div>
    <div class="mt-2">
        <ul class="list-group list-group-flush">
         <li class="list-group-item">
             <div class="d-flex justify-content-between text-body-secondary">
                 <div class="user-info">
                     <img src="{% static 'image/zhen1.png' %}" class="rounded-circle" height="40" width="40" alt="">
                     <span class="mt-2">鸩</span>
                 </div>
                 <div class="creat-time" style="line-height: 40px">2024年12月26日 16:30</div>
             </div>
            <div class="mt-3">这是评论内容</div>
         </li>
        </ul>
    </div>
</main>
</body>
</html>

templates/html备份/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>不知冬的博客</title>
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>

<header class="p-3 text-bg-info border-bottom border-warning mb-4">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img src="{% static 'image/lafei.png' %}" height="45" alt="">
                <!-- alt参数指定图片的替代文字，如果图片无法加载，浏览器会显示这个文本 -->
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="#" class="nav-link px-2 text-secondary">首页</a></li>
                <li><a href="#" class="nav-link px-2 text-light">发布博客</a></li>

            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                <input type="search" class="form-control form-control-dark text-bg-light" placeholder="搜索..."
                       aria-label="Search">
            </form>

            <div class="text-end">
                <button type="button" class="btn btn-warning me-2">登录</button>
                <button type="button" class="btn btn-outline-light">注册</button>
            </div>
        </div>
    </div>
</header>
<main class="container bg-white p-3 rounded">
    <h1>博客列表</h1>
    <div class="row row-cols-2 row-gap-4">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <a href="#">Django项目实战</a>
                </div>
                <div class="card-body" style="height: 100px;">
                    <p class="card-text">
                        With supporting text below as a natural lead-in to additional content.
                    </p>
                </div>
                <div class="card-footer text-body-secondary d-flex justify-content-between">
                    <div>
                        <img src="{% static 'image/zhen1.png' %}" alt="" class="rounded-circle" width="30" height="30">
                        鸩
                    </div>
                    <div>发布时间：2024.12.26 15:06</div>
                </div>
            </div>
        </div>

    </div>

</main>
</body>
</html>

templates/html备份/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>不知冬的博客</title>
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>

<header class="p-3 text-bg-info border-bottom border-warning mb-4">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img src="{% static 'image/lafei.png' %}" height="45" alt="">
                <!-- alt参数指定图片的替代文字，如果图片无法加载，浏览器会显示这个文本 -->
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="#" class="nav-link px-2 text-secondary">首页</a></li>
                <li><a href="#" class="nav-link px-2 text-light">发布博客</a></li>

            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                <input type="search" class="form-control form-control-dark text-bg-light" placeholder="搜索..."
                       aria-label="Search">
            </form>

            <div class="text-end">
                <button type="button" class="btn btn-warning me-2">登录</button>
                <button type="button" class="btn btn-outline-light">注册</button>
            </div>
        </div>
    </div>
</header>
<main class="container bg-white p-3 rounded">
    <div style="max-width: 330px" class="m-auto">
        <h1>登录</h1>
        <form action="" method="POST">
            <div class="mb-3">
                <label>邮箱</label>
                <input type="email" name="email" class="form-control" placeholder="邮箱">
            </div>
            <div class="mb-3">
                <label>密码</label>
                <input type="password" name="password" class="form-control" placeholder="密码">
            </div>
            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" name="remenber" value="1" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                    记住我
                </label>
            </div>
        </form>
        <div class="mb-3">
            <button class="btn btn-primary w-100">立即登录</button>
        </div>
    </div>

</main>
</body>
</html>

templates/html备份/pub_blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>不知冬的博客</title>
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'wangeditor/style.css' %}">
    <script src="{% static 'wangeditor/index.js' %}"></script>
    <script src="{% static 'js/pub_blog.js' %}"></script>
    <style>
        #editor—wrapper {
            border: 1px solid #ccc;
            z-index: 100; /* 按需定义 */
        }
        #toolbar-container {
            border-bottom: 1px solid #ccc;
        }
        #editor-container {
            height: 500px;
        }
    </style>
</head>
<body>

<header class="p-3 text-bg-info border-bottom border-warning mb-4">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img src="{% static 'image/lafei.png' %}" height="45" alt="">
                <!-- alt参数指定图片的替代文字，如果图片无法加载，浏览器会显示这个文本 -->
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="#" class="nav-link px-2 text-secondary">首页</a></li>
                <li><a href="#" class="nav-link px-2 text-light">发布博客</a></li>

            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                <input type="search" class="form-control form-control-dark text-bg-light" placeholder="搜索..."
                       aria-label="Search">
            </form>

            <div class="text-end">
                <button type="button" class="btn btn-warning me-2">登录</button>
                <button type="button" class="btn btn-outline-light">注册</button>
            </div>
        </div>
    </div>
</header>
<main class="container bg-white p-3 rounded">
    <h1>发布博客</h1>
    <div class="mt-3">
        <form action="" method="POST">
            <div class="mb-3">
                <label for="title" class="form-label">标题</label>
                <input type="text" class="form-control" id="title" name="title">
            </div>
            <div class="mb-3">
                <label for="category" class="form-label">分类</label>
                <select class="form-select" id="category" name="category">
                    <option value="1">Python</option>
                    <option value="2">前端</option>
                </select>
            </div>
            <div class="mb-3">
                <lable class="form-label">内容</lable>
                <div id="editor—wrapper">
                    <div id="toolbar-container"><!-- 工具栏 --></div>
                    <div id="editor-container"><!-- 编辑器 --></div>
                </div>
            </div>
            <div class="mb-3 text-end">
                <button class="btn btn-primary">发布</button>
            </div>
        </form>
    </div>

</main>
</body>
</html>

templates/html备份/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>不知冬的博客</title>
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>

<header class="p-3 text-bg-info border-bottom border-warning mb-4">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img src="{% static 'image/lafei.png' %}" height="45" alt="">
                <!-- alt参数指定图片的替代文字，如果图片无法加载，浏览器会显示这个文本 -->
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="#" class="nav-link px-2 text-secondary">首页</a></li>
                <li><a href="#" class="nav-link px-2 text-light">发布博客</a></li>

            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                <input type="search" class="form-control form-control-dark text-bg-light" placeholder="搜索..."
                       aria-label="Search">
            </form>

            <div class="text-end">
                <button type="button" class="btn btn-warning me-2">登录</button>
                <button type="button" class="btn btn-outline-light">注册</button>
            </div>
        </div>
    </div>
</header>
<main class="container bg-white p-3 rounded">
    <div style="max-width: 330px" class="m-auto">
        <h1>注册</h1>
        <form action="" method="POST">
            <div class="mb-3">
                <label>用户名</label>
                <input type="text" name="username" class="form-control" placeholder="用户名">
            </div>
            <div class="mb-3">
                <label>邮箱</label>
                <input type="email" name="email" class="form-control" placeholder="邮箱">
            </div>
            <div class="mb-3">
                <label>验证码</label>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="验证码"
                           aria-label="Recipient's username" aria-describedby="button-addon2">
                    <button class="btn btn-outline-secondary" type="button">获取验证码</button>
                </div>
            </div>
            <div class="mb-3">
                <label>密码</label>
                <input type="password" name="password" class="form-control" placeholder="密码">
            </div>

        </form>
        <div class="mb-3">
            <button class="btn btn-primary w-100">立即注册</button>
        </div>
    </div>


</main>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}
	首页
{% endblock %}

{% block main %}
    <h1>博客列表</h1>
    <div class="row row-cols-2 row-gap-4">
    {% for blog in blogs %}
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <a href="{% url 'blog:blog_detail' blog_id=blog.id %}">{{ blog.title }}</a>
                </div>
                <div class="card-body" style="height: 120px;">
                    <p class="card-text">
                        {{ blog.content|striptags|truncatechars:150 }}<!-- 忽略html标签，且最大只显示200字符 -->
                    </p>
                </div>
                <div class="card-footer text-body-secondary d-flex justify-content-between">
                    <div>
                        <img src="{% static 'image/zhen1.png' %}" alt="" class="rounded-circle" width="30" height="30">
                        {{ blog.author.username }}
                    </div>
                    <div>发布时间:{{ blog.pub_time|date:"Y年m月d日 H时i分" }}</div>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}
	登录
{% endblock %}

{% block main %}

    <div style="max-width: 330px" class="m-auto">
        <h1>登录</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label>邮箱</label>
                <input type="email" name="email" class="form-control" placeholder="邮箱">
            </div>
            <div class="mb-3">
                <label>密码</label>
                <input type="password" name="password" class="form-control" placeholder="密码">
            </div>
            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" name="remenber" value="1" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                    14天内免登录
                </label>
            </div>
        <div class="mb-3">
            <button class="btn btn-primary w-100">立即登录</button>
        </div>        
        </form>
    </div>
	
{% endblock %}